// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import (
	"context"

	"github.com/reation/home_user_service/proto/types/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Id               = proto.Id
	IdRequest        = proto.IdRequest
	OrderInfo        = proto.OrderInfo
	UserInfoResponse = proto.UserInfoResponse
	UserOrderList    = proto.UserOrderList

	User interface {
		GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		GetUserOrderList(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserOrderList, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) GetUserOrderList(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*UserOrderList, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetUserOrderList(ctx, in, opts...)
}
